### ISSUE TITLE
Chess Pieces Fail to Render on Desktop

### ISSUE THREAD

**Issue by BornIncompetence** [adam-mcdaniel/chess-engine#4]
Tested on Windows 10, Rust Ver. 1.49.0

**Expected**: Pieces actually render as shown in the example images

**Actual behavior**: Pieces show up as thin white squares on the board
![image](https://user-images.githubusercontent.com/28491322/106094287-9a282980-60e6-11eb-8a4f-2e7209ae2c38.png)

**Comment by adam-mcdaniel** [comment]
Hmm, this is very strange, especially since the chess pieces aren't images. They're just the unicode text representations for each of the pieces :/ I'm not exactly sure how to go about fixing this other than using images

**Comment by BornIncompetence** [comment]
From what I could gather, the font that iced uses by default, `Lato`, doesn't have chess piece glyphs, but it's weird that you're able to render the pieces still. I loaded in `DejaVuSansMono` just to test and I'm able to get the pieces to render. (after fixing a weird Unicode typo that misaligns the pawns)

![image](https://user-images.githubusercontent.com/28491322/106541407-e0023a80-64b6-11eb-9fd0-41a5923a93f9.png)
